services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: mysecretpassword
      APP_USER: app_user
      APP_USER_PASSWORD: app_password
    volumes:
      - ./volumes/database:/opt/oracle/oradata
    healthcheck:
      test: [ "CMD", "sqlplus", "-L", "app_user/app_password@//localhost:1521/XEPDB1" ]
      interval: 10s
      timeout: 10s
      retries: 10
    mem_limit: 2g
    restart: always

