spring:
  application:
    name: spring-api
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 10000
mybatis:
  # mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cbo.layered.infrastructure.mybatis
  type-handlers-package: com.cbo.layered.infrastructure.mybatis
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    default-lazy-load-type: proxy

server:
  port: 8092

