spring:
  application:
    name: spring-api
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 10000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8092

