spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${DB_ADMIN_USER:app_user}
    password: ${DB_ADMIN_USER_PASS:app_password}

  flyway:
    user: ${DB_ADMIN_USER:app_user}
    password: ${DB_ADMIN_USER_PASS:app_password}
    baseline-on-migrate: true
    baseline-version: 1

mybatis:
  type-aliases-package: com.cbo.layered.infrastructure.mybatis
  type-handlers-package: com.cbo.layered.infrastructure.mybatis
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    default-lazy-load-type: proxy
