spring:
  application:
    name: user-account-service

  # Fallback profile: arranca con H2 si no hay perfil activo
  datasource:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  hikari:
    maximum-pool-size: 5
    minimum-idle: 1

  flyway:
    enabled: true
    locations: classpath:db/migration

mybatis:
  type-aliases-package: com.cbo.layered.infrastructure.mybatis
  type-handlers-package: com.cbo.layered.infrastructure.mybatis
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    default-lazy-load-type: proxy

server:
  port: 8092
  servlet:
    context-path: /api/v1
