### List all clients
GET http://localhost:8092/api/v1/client
Accept: application/json

### Get a client by ID
GET http://localhost:8092/api/v1/client/3a0cbd5a-ab03-4840-ab50-73062cc5c099
Accept: application/json

### Create a new client
POST http://localhost:8092/api/v1/client
Content-Type: application/json
Accept: application/json

{
  "name": "New Client",
  "surname": "new-client",
  "phone": "1234567890100000",
  "email": "new-client02@gmail.com"
 }

### Update a client by ID
PUT http://localhost:8092/api/v1/client/20e0b61a-f317-4a1f-9494-0a4b86d97ac9
Content-Type: application/json
Accept: application/json

{
  "name": "Updated Client",
  "surname": "updated-client",
  "phone": "1234567890123",
  "email": "updated-client01@gmail.com"
}

### Delete a client by ID
DELETE http://localhost:8092/api/v1/client/12dc49ea-c918-4322-9d10-7dd447e3c0cf
Accept: application/json
