### List all clients
GET http://localhost:8092/api/v1/client
Accept: application/json

### Get a client by ID
GET http://localhost:8092/api/v1/client/95ae9e6d-4829-4274-82f8-573546724770
Accept: application/json

