### Create a new User
PUT http://localhost:8092/api/v1/users/cb9cf160-5f2b-4d05-baf6-c7833662b309
Content-Type: application/json
Accept: application/json

{
  "id": "cb9cf160-5f2b-4d05-baf6-c7833662b309",
  "firstName": "Carlos",
  "lastName": "Balsalobre",
  "email": "new-client02@gmail.com",
  "phoneNumber": "+34 666 666 666",
    "username": "carlitos",
    "rawPassword": "P@ssw0rd!",
    "nationalId": "12345678A",
    "dateOfBirth": "1990-01-01",
    "address": {
      "street": "Calle de Vallehermoso",
      "city": "Madrid",
      "state": "Madrid",
      "country": "Spain",
      "postalCode": "28015"
    },
    "createdBy": "admin"
}